In [87]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score,train_test_split, KFold, cross_val_predict
from sklearn.metrics import mean_squared_error,r2_score,roc_curve,auc,precision_recall_curve, accuracy_score, mean_absolute_error, \
recall_score, precision_score, confusion_matrix
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, ParameterGrid, StratifiedKFold, RandomizedSearchCV
from sklearn.ensemble import VotingRegressor, VotingClassifier, StackingRegressor, StackingClassifier, GradientBoostingRegressor,GradientBoostingClassifier, BaggingRegressor,BaggingClassifier,RandomForestRegressor,RandomForestClassifier,AdaBoostRegressor,AdaBoostClassifier
from sklearn.linear_model import LinearRegression,LogisticRegression, LassoCV, RidgeCV, ElasticNetCV
from sklearn.neighbors import KNeighborsRegressor
import itertools as it
import time as time
import xgboost as xgb
from pyearth import Earth
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
data = pd.read_csv('./Data/salary_data_cleaned.csv')
import warnings
warnings.filterwarnings(
    "ignore")

In [88]:
data = data.drop(columns='Unnamed: 0')
data

,totalyearlycompensation,yearsofexperience,yearsatcompany,Masters_Degree,Bachelors_Degree,Doctorate_Degree,Highschool,Some_College,Race_Asian,Race_White,...,dmaid_770,dmaid_789,dmaid_803,dmaid_807,dmaid_819,dmaid_820,dmaid_825,dmaid_855,dmaid_862,dmaid_other
0,400000,5.0,5.0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
1,136000,3.0,2.0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,337000,6.0,6.0,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
3,222000,4.0,4.0,1,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,187000,5.0,0.0,0,1,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21586,1470000,9.0,7.0,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
21587,4500000,20.0,14.0,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
21588,1605000,16.0,2.0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
21589,2372000,22.0,2.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
21590,4980000,17.0,0.0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1

In [163]:
data.yearsofexperience.value_counts()

5.0     2168
3.0     2017
2.0     2015
4.0     1719
10.0    1562
1.0     1433
0.0     1429
6.0     1409
8.0     1239
7.0     1227
15.0     903
9.0      711
12.0     659
20.0     610
11.0     421
13.0     389
14.0     380
16.0     249
18.0     207
17.0     182
25.0     155
19.0      86
22.0      83
21.0      81
23.0      55
24.0      52
30.0      46
26.0      23
27.0      17
28.0      16
35.0      15
29.0       8
40.0       6
32.0       5
36.0       3
38.0       3
33.0       3
39.0       2
31.0       1
37.0       1
45.0       1
Name: yearsofexperience, dtype: int64

In [3]:
data.totalyearlycompensation.describe()

count    2.159100e+04
mean     1.978458e+05
std      1.330927e+05
min      1.000000e+04
25%      1.190000e+05
50%      1.730000e+05
75%      2.450000e+05
max      4.980000e+06
Name: totalyearlycompensation, dtype: float64

In [219]:
transformed_data = data
transformed_data.totalyearlycompensation = transformed_data.totalyearlycompensation.apply(lambda x: np.log(x))

In [220]:
transformed_data.totalyearlycompensation.describe()

count    21591.000000
mean        12.003547
std          0.657253
min          9.210340
25%         11.686879
50%         12.061047
75%         12.409013
max         15.420940
Name: totalyearlycompensation, dtype: float64

In [64]:
X_train = pd.read_csv('./Data/X_train.csv').drop(columns='Unnamed: 0')
y_train = pd.read_csv('./Data/y_train.csv').drop(columns='Unnamed: 0')
X_test = pd.read_csv('./Data/X_test.csv').drop(columns='Unnamed: 0')
y_test = pd.read_csv('./Data/y_test.csv').drop(columns='Unnamed: 0')

In [95]:
data.columns = data.columns.str.replace(' ', '_')

In [99]:
data.columns = data.columns.str.replace('(', '_')
data.columns = data.columns.str.replace(')', '_')

In [103]:
data.columns = data.columns.str.replace('/', '_')

In [107]:
data.columns = data.columns.str.replace('-', '_')

In [153]:
col = data.columns
col = [str(x) for x in col]

In [156]:
model = sm.ols(formula = 'totalyearlycompensation~' + '+'.join([x for x in col]), data = train_df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               OLS Regression Results
===================================================================================
Dep. Variable:     totalyearlycompensation   R-squared:                       1.000
Model:                                 OLS   Adj. R-squared:                  1.000
Method:                      Least Squares   F-statistic:                 1.130e+31
Date:                     Mon, 22 May 2023   Prob (F-statistic):               0.00
Time:                             22:42:19   Log-Likelihood:             2.6062e+05
No. Observations:                    12954   AIC:                        -5.210e+05
Df Residuals:                        12853   BIC:                        -5.203e+05
Df Model:                              100
Covariance Type:                 nonrobust
======================================================================================================
                                         coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
Intercept                           2.256e-10   1.65e-10      1.369      0.171   -9.74e-11    5.48e-10
totalyearlycompensation                1.0000   4.18e-17   2.39e+16      0.000       1.000       1.000
yearsofexperience                  -4.775e-12   9.46e-13     -5.048      0.000   -6.63e-12   -2.92e-12
yearsatcompany                       1.11e-11   1.45e-12      7.630      0.000    8.25e-12     1.4e-11
Masters_Degree                      3.638e-12   3.15e-10      0.012      0.991   -6.14e-10    6.21e-10
Bachelors_Degree                    1.201e-10   3.15e-10      0.381      0.703   -4.97e-10    7.37e-10
Doctorate_Degree                    1.273e-11   3.16e-10      0.040      0.968   -6.06e-10    6.31e-10
Highschool                         -2.692e-10   3.17e-10     -0.850      0.395    -8.9e-10    3.52e-10
Some_College                        2.183e-11   3.17e-10      0.069      0.945   -5.99e-10    6.43e-10
Race_Asian                          6.139e-12    3.4e-11      0.181      0.857   -6.04e-11    7.27e-11
Race_White                          4.366e-11   3.42e-11      1.277      0.201   -2.33e-11    1.11e-10
Race_Two_Or_More                    9.004e-11   3.74e-11      2.406      0.016    1.67e-11    1.63e-10
Race_Black                          3.956e-11   3.79e-11      1.043      0.297   -3.48e-11    1.14e-10
Race_Hispanic                       9.732e-11   3.65e-11      2.667      0.008    2.58e-11    1.69e-10
company_amazon                      1.728e-11   2.19e-11      0.788      0.431   -2.57e-11    6.03e-11
company_apple                       3.456e-11   2.76e-11      1.252      0.211   -1.95e-11    8.87e-11
company_cisco                       -7.64e-11    3.4e-11     -2.247      0.025   -1.43e-10   -9.75e-12
company_facebook                    2.109e-11   2.56e-11      0.823      0.411   -2.91e-11    7.13e-11
company_google                     -1.046e-10   2.37e-11     -4.421      0.000   -1.51e-10   -5.82e-11
company_ibm                         1.819e-11   3.29e-11      0.553      0.580   -4.63e-11    8.27e-11
company_intel                       3.488e-10   3.84e-11      9.082      0.000    2.74e-10    4.24e-10
company_microsoft                   1.273e-11   2.23e-11      0.571      0.568    -3.1e-11    5.64e-11
company_oracle                     -4.184e-11   3.15e-11     -1.330      0.183   -1.03e-10    1.98e-11
company_other                      -8.185e-12   1.75e-11     -0.468      0.640   -4.24e-11    2.61e-11
company_salesforce                  1.023e-11   3.42e-11      0.300      0.765   -5.67e-11    7.72e-11
level_E5                            1.437e-10    4.1e-11      3.507      0.000    6.34e-11    2.24e-10
level_IC4                          -3.547e-11    3.7e-11     -0.960      0.337   -1.08e-10     3.7e-11
level_L1                            3.795e-10   3.24e-11     11.729      0.000    3.16e-10    4.43e-10
level_L2                            -1.21e-10   2.79e-11     -4.329      0.000   -1.76e-10   -6.62e-11
level_L3                            3.638e-12   2.24e-11      0.162      0.871   -4.03e-11    4.76e-11
level_L4                           -4.184e-11    2.1e-11     -1.993      0.046    -8.3e-11   -6.85e-13
level_L5                           -2.547e-11   2.18e-11     -1.167      0.243   -6.83e-11    1.73e-11
level_L6                           -9.186e-11   2.51e-11     -3.655      0.000   -1.41e-10   -4.26e-11
level_L7                           -1.528e-10   3.62e-11     -4.226      0.000   -2.24e-10   -8.19e-11
level_Senior_Software_Engineer      9.936e-11      3e-11      3.317      0.001    4.06e-11    1.58e-10
level_other                         1.046e-11   1.77e-11      0.591      0.555   -2.42e-11    4.52e-11
title_Business_Analyst              3.081e-10   2.97e-11     10.375      0.000     2.5e-10    3.66e-10
title_Data_Scientist                9.186e-11   2.49e-11      3.687      0.000     4.3e-11    1.41e-10
title_Hardware_Engineer              1.56e-10   2.62e-11      5.959      0.000    1.05e-10    2.07e-10
title_Management_Consultant        -1.104e-09   3.08e-11    -35.797      0.000   -1.16e-09   -1.04e-09
title_Product_Designer               8.64e-11   4.11e-11      2.102      0.036    5.83e-12    1.67e-10
title_Product_Manager               1.646e-10   2.62e-11      6.278      0.000    1.13e-10    2.16e-10
title_Software_Engineer             6.185e-11   1.85e-11      3.340      0.001    2.55e-11    9.81e-11
title_Software_Engineering_Manager  9.459e-11   2.48e-11      3.808      0.000    4.59e-11    1.43e-10
title_Solution_Architect            1.158e-10   3.15e-11      3.682      0.000    5.42e-11    1.78e-10
title_Technical_Program_Manager     9.913e-11   2.67e-11      3.712      0.000    4.68e-11    1.51e-10
title_other                         2.024e-10   2.27e-11      8.903      0.000    1.58e-10    2.47e-10
tag_API_Development__Back_End_     -1.132e-10   2.06e-11     -5.502      0.000   -1.54e-10   -7.29e-11
tag_Data                           -6.253e-11   2.48e-11     -2.522      0.012   -1.11e-10   -1.39e-11
tag_DevOps                         -3.456e-11      3e-11     -1.151      0.250   -9.34e-11    2.43e-11
tag_Distributed_Systems__Back_End_  1.273e-10   1.96e-11      6.483      0.000    8.88e-11    1.66e-10
tag_Full_Stack                     -5.014e-11   1.91e-11     -2.623      0.009   -8.76e-11   -1.27e-11
tag_ML___AI                        -1.796e-11    2.4e-11     -0.748      0.455    -6.5e-11    2.91e-11
tag_Product                        -1.291e-10   3.01e-11     -4.288      0.000   -1.88e-10   -7.01e-11
tag_Technical                      -4.729e-11   3.24e-11     -1.458      0.145   -1.11e-10    1.63e-11
tag_User_Experience__UX_            8.768e-10    4.8e-11     18.252      0.000    7.83e-10    9.71e-10
tag_Web_Development__Front_End_      -1.1e-10   2.36e-11     -4.666      0.000   -1.56e-10   -6.38e-11
tag_other                          -1.019e-10   1.78e-11     -5.715      0.000   -1.37e-10   -6.69e-11
gender_Female                       9.004e-11   5.73e-11      1.572      0.116   -2.22e-11    2.02e-10
gender_Male                         1.019e-10   5.71e-11      1.785      0.074   -9.99e-12    2.14e-10
gender_Other                        6.457e-11   6.78e-11      0.952      0.341   -6.84e-11    1.98e-10
dmaid_0                            -1.546e-11   1.64e-11     -0.943      0.346   -4.76e-11    1.67e-11
dmaid_501                           5.457e-11   1.94e-11      2.812      0.005    1.65e-11    9.26e-11
dmaid_504                           4.025e-11   4.48e-11      0.899      0.369   -4.75e-11    1.28e-10
dmaid_505                           3.065e-10   6.15e-11      4.981      0.000    1.86e-10    4.27e-10
dmaid_506                           -5.73e-11   2.69e-11     -2.128      0.033    -1.1e-10   -4.51e-12
dmaid_508                          -5.821e-11   6.59e-11     -0.883      0.377   -1.87e-10     7.1e-11
dmaid_511                           8.063e-10   2.81e-11     28.662      0.000    7.51e-10    8.61e-10
dmaid_512                          -7.276e-12   1.01e-10     -0.072      0.943   -2.05e-10    1.91e-10
dmaid_515                           1.655e-10   1.17e-10      1.412      0.158   -6.43e-11    3.95e-10
dmaid_517                          -1.073e-10   6.94e-11     -1.545      0.122   -2.43e-10    2.88e-11
dmaid_521                          -1.528e-10   1.96e-10     -0.781      0.435   -5.36e-10     2.3e-10
dmaid_524                           4.593e-10   3.89e-11     11.800      0.000    3.83e-10    5.36e-10
dmaid_527                           1.673e-10   9.23e-11      1.814      0.070   -1.35e-11    3.48e-10
dmaid_528                           7.276e-12   8.69e-11      0.084      0.933   -1.63e-10    1.78e-10
dmaid_533                          -3.211e-10   1.39e-10     -2.317      0.021   -5.93e-10   -4.95e-11
dmaid_534                           8.004e-11   8.22e-11      0.974      0.330    -8.1e-11    2.41e-10
dmaid_535                          -1.783e-10   8.08e-11     -2.206      0.027   -3.37e-10   -1.99e-11
dmaid_539                          -6.912e-11   1.17e-10     -0.589      0.556   -2.99e-10    1.61e-10
dmaid_556                           4.547e-11   8.21e-11      0.554      0.580   -1.15e-10    2.06e-10
dmaid_560                           1.928e-10      5e-11      3.860      0.000    9.49e-11    2.91e-10
dmaid_602                           -1.59e-09   3.44e-11    -46.205      0.000   -1.66e-09   -1.52e-09
dmaid_609                           2.692e-10   8.35e-11      3.223      0.001    1.06e-10    4.33e-10
dmaid_613                           1.273e-11   5.55e-11      0.229      0.819   -9.61e-11    1.22e-10
dmaid_616                          -4.002e-11   6.95e-11     -0.576      0.565   -1.76e-10    9.62e-11
dmaid_617                          -6.912e-11   1.78e-10     -0.387      0.699   -4.19e-10    2.81e-10
dmaid_618                           2.146e-10   6.05e-11      3.546      0.000     9.6e-11    3.33e-10
dmaid_623                           4.547e-11   3.23e-11      1.409      0.159   -1.78e-11    1.09e-10
dmaid_635                              -1e-10   2.64e-11     -3.791      0.000   -1.52e-10   -4.83e-11
dmaid_641                           2.183e-11   9.86e-11      0.221      0.825   -1.72e-10    2.15e-10
dmaid_652                           8.185e-11   1.65e-10      0.495      0.621   -2.42e-10    4.06e-10
dmaid_659                            1.31e-10    1.1e-10      1.191      0.234   -8.45e-11    3.46e-10
dmaid_669                          -4.263e-11   9.85e-11     -0.433      0.665   -2.36e-10     1.5e-10
dmaid_670                           8.549e-11   8.66e-11      0.987      0.324   -8.43e-11    2.55e-10
dmaid_675                           2.583e-10   1.78e-10      1.447      0.148   -9.15e-11    6.08e-10
dmaid_751                           2.201e-10   4.32e-11      5.098      0.000    1.35e-10    3.05e-10
dmaid_753                          -1.637e-11   4.83e-11     -0.339      0.735   -1.11e-10    7.84e-11
dmaid_757                          -5.675e-10   1.46e-10     -3.885      0.000   -8.54e-10   -2.81e-10
dmaid_770                           3.638e-11   6.16e-11      0.591      0.555   -8.43e-11    1.57e-10
dmaid_789                            1.31e-10   1.65e-10      0.792      0.428   -1.93e-10    4.55e-10
dmaid_803                           1.091e-11    2.9e-11      0.377      0.706   -4.59e-11    6.77e-11
dmaid_807                           1.037e-10   1.67e-11      6.213      0.000     7.1e-11    1.36e-10
dmaid_819                           4.911e-11   1.86e-11      2.640      0.008    1.26e-11    8.56e-11
dmaid_820                           1.683e-11   4.12e-11      0.409      0.683   -6.39e-11    9.75e-11
dmaid_825                          -2.728e-11   3.83e-11     -0.713      0.476   -1.02e-10    4.78e-11
dmaid_855                          -1.651e-10   1.14e-10     -1.454      0.146   -3.88e-10    5.75e-11
dmaid_862                          -1.746e-10   8.31e-11     -2.101      0.036   -3.38e-10   -1.17e-11
dmaid_other                         1.892e-10   3.84e-11      4.923      0.000    1.14e-10    2.65e-10
==============================================================================
Omnibus:                     6928.162   Durbin-Watson:                   1.804
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           227066.192
Skew:                           1.971   Prob(JB):                         0.00
Kurtosis:                      23.128   Cond. No.                     1.26e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.6e-20. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [159]:
X = data.drop(columns = ['totalyearlycompensation'])
y = data.totalyearlycompensation

from sklearn.model_selection import train_test_split
X_train, X_test, y_train,\
y_test = train_test_split(X, y, test_size = 0.4, random_state = 1)

In [160]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

LinearRegression()

In [200]:
train_df, test_df = train_test_split(data, test_size=0.4, random_state=1)

In [210]:
test_df

,totalyearlycompensation,yearsofexperience,yearsatcompany,Masters_Degree,Bachelors_Degree,Doctorate_Degree,Highschool,Some_College,Race_Asian,Race_White,...,dmaid_770,dmaid_789,dmaid_803,dmaid_807,dmaid_819,dmaid_820,dmaid_825,dmaid_855,dmaid_862,dmaid_other
20736,95000,8.0,1.0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15542,125000,9.0,2.0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6120,350000,15.0,5.0,0,1,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
12332,108000,4.0,0.0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1113,113000,6.0,3.0,0,1,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12492,214000,0.0,0.0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9528,155000,2.0,2.0,0,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
649,160000,4.0,1.0,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
4604,200000,5.0,2.0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
11932,161000,6.0,6.0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [208]:
test_df.loc[test_df.totalyearlycompensation == 159000.0].loc[test_df.yearsatcompany == 1.0]

,totalyearlycompensation,yearsofexperience,yearsatcompany,Masters_Degree,Bachelors_Degree,Doctorate_Degree,Highschool,Some_College,Race_Asian,Race_White,...,dmaid_770,dmaid_789,dmaid_803,dmaid_807,dmaid_819,dmaid_820,dmaid_825,dmaid_855,dmaid_862,dmaid_other
5551,159000,1.0,1.0,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
2220,159000,1.0,1.0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
10382,159000,1.0,1.0,0,1,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
15705,159000,5.0,1.0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9763,159000,1.0,1.0,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0

In [209]:
test_df.iloc[3415,:]

totalyearlycompensation    159000.0
yearsofexperience               1.0
yearsatcompany                  1.0
Masters_Degree                  0.0
Bachelors_Degree                1.0
                             ...
dmaid_820                       0.0
dmaid_825                       0.0
dmaid_855                       0.0
dmaid_862                       0.0
dmaid_other                     0.0
Name: 9763, Length: 107, dtype: float64

In [211]:
test_df = test_df.drop(labels=9763)

In [212]:
test_df

,totalyearlycompensation,yearsofexperience,yearsatcompany,Masters_Degree,Bachelors_Degree,Doctorate_Degree,Highschool,Some_College,Race_Asian,Race_White,...,dmaid_770,dmaid_789,dmaid_803,dmaid_807,dmaid_819,dmaid_820,dmaid_825,dmaid_855,dmaid_862,dmaid_other
20736,95000,8.0,1.0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15542,125000,9.0,2.0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6120,350000,15.0,5.0,0,1,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
12332,108000,4.0,0.0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1113,113000,6.0,3.0,0,1,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12492,214000,0.0,0.0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9528,155000,2.0,2.0,0,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
649,160000,4.0,1.0,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
4604,200000,5.0,2.0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
11932,161000,6.0,6.0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [115]:
train = pd.concat([X_train, y_train])
test = pd.concat([X_test, y_test])

In [124]:
model = sm.ols(formula = 'totalyearlycompensation~' + alll, data = train_df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               OLS Regression Results
===================================================================================
Dep. Variable:     totalyearlycompensation   R-squared:                       1.000
Model:                                 OLS   Adj. R-squared:                  1.000
Method:                      Least Squares   F-statistic:                 6.826e+30
Date:                     Mon, 22 May 2023   Prob (F-statistic):               0.00
Time:                             12:06:46   Log-Likelihood:             2.5735e+05
No. Observations:                    12954   AIC:                        -5.145e+05
Df Residuals:                        12853   BIC:                        -5.137e+05
Df Model:                              100
Covariance Type:                 nonrobust
======================================================================================================
                                         coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
Intercept                           1.874e-10   2.16e-10      0.869      0.385   -2.35e-10     6.1e-10
totalyearlycompensation                1.0000   5.38e-17   1.86e+16      0.000       1.000       1.000
yearsofexperience                   6.594e-12   1.22e-12      5.418      0.000    4.21e-12    8.98e-12
yearsatcompany                      5.294e-12   1.87e-12      2.828      0.005    1.63e-12    8.96e-12
Masters_Degree                     -1.564e-10   4.05e-10     -0.386      0.699   -9.51e-10    6.38e-10
Bachelors_Degree                    3.783e-10   4.05e-10      0.934      0.350   -4.16e-10    1.17e-09
Doctorate_Degree                    4.366e-11   4.06e-10      0.108      0.914   -7.52e-10     8.4e-10
Highschool                         -7.276e-12   4.08e-10     -0.018      0.986   -8.06e-10    7.92e-10
Some_College                        8.004e-11   4.07e-10      0.196      0.844   -7.19e-10    8.79e-10
Race_Asian                          6.287e-11   4.44e-11      1.416      0.157   -2.42e-11     1.5e-10
Race_White                          9.186e-11   4.46e-11      2.058      0.040    4.37e-12    1.79e-10
Race_Two_Or_More                     7.89e-11   4.88e-11      1.617      0.106   -1.67e-11    1.75e-10
Race_Black                         -1.683e-11   4.94e-11     -0.340      0.734   -1.14e-10    8.01e-11
Race_Hispanic                        8.64e-11   4.76e-11      1.815      0.070   -6.93e-12     1.8e-10
company_amazon                      3.638e-11   2.85e-11      1.278      0.201   -1.94e-11    9.22e-11
company_apple                      -6.003e-11   3.57e-11     -1.681      0.093    -1.3e-10    9.98e-12
company_cisco                      -7.822e-11   4.39e-11     -1.781      0.075   -1.64e-10    7.85e-12
company_facebook                   -1.112e-10   3.31e-11     -3.354      0.001   -1.76e-10   -4.62e-11
company_google                      4.638e-11   3.06e-11      1.513      0.130   -1.37e-11    1.06e-10
company_ibm                        -5.457e-12   4.24e-11     -0.129      0.898   -8.86e-11    7.76e-11
company_intel                       3.474e-10   4.96e-11      7.005      0.000     2.5e-10    4.45e-10
company_microsoft                  -7.276e-12   2.89e-11     -0.252      0.801    -6.4e-11    4.94e-11
company_oracle                     -6.139e-11   4.06e-11     -1.512      0.131   -1.41e-10    1.82e-11
company_other                       7.458e-11   2.28e-11      3.274      0.001    2.99e-11    1.19e-10
company_salesforce                 -2.126e-11   4.41e-11     -0.482      0.630   -1.08e-10    6.52e-11
level_E5                            1.819e-12   5.29e-11      0.034      0.973   -1.02e-10    1.05e-10
level_IC4                           1.319e-11   4.77e-11      0.276      0.782   -8.03e-11    1.07e-10
level_L1                            3.738e-10   4.17e-11      8.956      0.000    2.92e-10    4.56e-10
level_L2                           -8.185e-11   3.61e-11     -2.267      0.023   -1.53e-10   -1.11e-11
level_L3                           -1.273e-11   2.91e-11     -0.438      0.661   -6.97e-11    4.42e-11
level_L4                            -5.73e-11   2.72e-11     -2.103      0.036   -1.11e-10   -3.89e-12
level_L5                            1.319e-11   2.83e-11      0.466      0.641   -4.23e-11    6.87e-11
level_L6                           -3.274e-11   3.25e-11     -1.007      0.314   -9.65e-11     3.1e-11
level_L7                           -8.367e-11   4.67e-11     -1.793      0.073   -1.75e-10    7.82e-12
level_Senior_Software_Engineer       6.73e-11   3.87e-11      1.740      0.082   -8.52e-12    1.43e-10
level_other                         3.774e-11   2.31e-11      1.637      0.102   -7.46e-12    8.29e-11
title_Business_Analyst              3.251e-10   3.84e-11      8.472      0.000     2.5e-10       4e-10
title_Data_Scientist                8.458e-11   3.23e-11      2.622      0.009    2.13e-11    1.48e-10
title_Hardware_Engineer             1.795e-10   3.38e-11      5.305      0.000    1.13e-10    2.46e-10
title_Management_Consultant        -1.173e-09   3.99e-11    -29.431      0.000   -1.25e-09    -1.1e-09
title_Product_Designer              1.692e-10    5.3e-11      3.191      0.001    6.53e-11    2.73e-10
title_Product_Manager               1.955e-10   3.39e-11      5.764      0.000    1.29e-10    2.62e-10
title_Software_Engineer             1.132e-10   2.41e-11      4.697      0.000     6.6e-11     1.6e-10
title_Software_Engineering_Manager  1.692e-10   3.22e-11      5.259      0.000    1.06e-10    2.32e-10
title_Solution_Architect            9.277e-11   4.06e-11      2.284      0.022    1.31e-11    1.72e-10
title_Technical_Program_Manager     5.639e-11   3.45e-11      1.632      0.103   -1.13e-11    1.24e-10
title_other                          1.81e-10   2.94e-11      6.149      0.000    1.23e-10    2.39e-10
tag_API_Development__Back_End_     -8.595e-11   2.67e-11     -3.218      0.001   -1.38e-10   -3.36e-11
tag_Data                           -8.731e-11   3.21e-11     -2.718      0.007    -1.5e-10   -2.43e-11
tag_DevOps                         -1.091e-10   3.88e-11     -2.813      0.005   -1.85e-10   -3.31e-11
tag_Distributed_Systems__Back_End_  6.912e-11   2.55e-11      2.709      0.007    1.91e-11    1.19e-10
tag_Full_Stack                     -2.424e-11   2.48e-11     -0.977      0.329   -7.29e-11    2.44e-11
tag_ML___AI                        -3.729e-11   3.11e-11     -1.199      0.231   -9.83e-11    2.37e-11
tag_Product                        -6.821e-11   3.89e-11     -1.752      0.080   -1.45e-10    8.09e-12
tag_Technical                       -3.82e-11   4.19e-11     -0.912      0.362    -1.2e-10    4.39e-11
tag_User_Experience__UX_            8.276e-10   6.19e-11     13.366      0.000    7.06e-10    9.49e-10
tag_Web_Development__Front_End_     -1.61e-10   3.05e-11     -5.270      0.000   -2.21e-10   -1.01e-10
tag_other                          -9.345e-11   2.32e-11     -4.029      0.000   -1.39e-10    -4.8e-11
gender_Female                        1.29e-10   7.48e-11      1.724      0.085   -1.76e-11    2.76e-10
gender_Male                         6.094e-11   7.45e-11      0.817      0.414   -8.52e-11    2.07e-10
gender_Other                        1.642e-10   8.83e-11      1.859      0.063   -8.91e-12    3.37e-10
dmaid_0                            -1.601e-10   4.88e-11     -3.277      0.001   -2.56e-10   -6.43e-11
dmaid_501                          -1.965e-10   5.05e-11     -3.889      0.000   -2.95e-10   -9.74e-11
dmaid_504                           1.346e-10   7.33e-11      1.836      0.066   -9.07e-12    2.78e-10
dmaid_505                           3.674e-10    9.2e-11      3.996      0.000    1.87e-10    5.48e-10
dmaid_506                           4.366e-11   5.61e-11      0.778      0.437   -6.63e-11    1.54e-10
dmaid_508                          -2.783e-10    9.7e-11     -2.869      0.004   -4.68e-10   -8.82e-11
dmaid_511                           7.749e-10   5.72e-11     13.549      0.000    6.63e-10    8.87e-10
dmaid_512                          -8.731e-11    1.4e-10     -0.624      0.532   -3.61e-10    1.87e-10
dmaid_515                           1.564e-10    1.6e-10      0.976      0.329   -1.58e-10    4.71e-10
dmaid_517                          -1.091e-10   1.01e-10     -1.078      0.281   -3.08e-10    8.93e-11
dmaid_521                          -6.548e-11   2.61e-10     -0.251      0.802   -5.77e-10    4.46e-10
dmaid_524                           4.202e-10   6.73e-11      6.243      0.000    2.88e-10    5.52e-10
dmaid_527                          -4.002e-11   1.29e-10     -0.311      0.756   -2.93e-10    2.13e-10
dmaid_528                          -8.731e-11   1.22e-10     -0.714      0.475   -3.27e-10    1.52e-10
dmaid_533                          -1.601e-10   1.87e-10     -0.855      0.393   -5.27e-10    2.07e-10
dmaid_534                          -5.548e-11   1.17e-10     -0.476      0.634   -2.84e-10    1.73e-10
dmaid_535                           4.366e-11   1.15e-10      0.380      0.704   -1.81e-10    2.69e-10
dmaid_539                           -2.31e-10    1.6e-10     -1.441      0.150   -5.45e-10    8.33e-11
dmaid_556                           4.002e-11   1.16e-10      0.344      0.731   -1.88e-10    2.68e-10
dmaid_560                           9.095e-11   7.85e-11      1.158      0.247    -6.3e-11    2.45e-10
dmaid_602                          -1.728e-09   6.29e-11    -27.468      0.000   -1.85e-09    -1.6e-09
dmaid_609                           3.747e-10   1.18e-10      3.173      0.002    1.43e-10    6.06e-10
dmaid_613                          -2.547e-11   8.51e-11     -0.299      0.765   -1.92e-10    1.41e-10
dmaid_616                           1.201e-10   1.01e-10      1.185      0.236   -7.85e-11    3.19e-10
dmaid_617                          -2.292e-10   2.39e-10     -0.960      0.337   -6.97e-10    2.39e-10
dmaid_618                          -2.219e-10   9.08e-11     -2.445      0.015      -4e-10    -4.4e-11
dmaid_623                          -7.276e-11   6.09e-11     -1.194      0.232   -1.92e-10    4.67e-11
dmaid_635                           -1.71e-10   5.57e-11     -3.070      0.002    -2.8e-10   -6.18e-11
dmaid_641                            1.71e-10   1.37e-10      1.250      0.211   -9.72e-11    4.39e-10
dmaid_652                          -7.276e-11   2.22e-10     -0.328      0.743   -5.07e-10    3.62e-10
dmaid_659                          -1.091e-10   1.51e-10     -0.723      0.470   -4.05e-10    1.87e-10
dmaid_669                          -4.366e-11   1.37e-10     -0.320      0.749   -3.11e-10    2.24e-10
dmaid_670                          -5.093e-11   1.22e-10     -0.417      0.676    -2.9e-10    1.88e-10
dmaid_675                           1.755e-10   2.39e-10      0.736      0.462   -2.92e-10    6.43e-10
dmaid_751                          -2.838e-10   7.16e-11     -3.965      0.000   -4.24e-10   -1.43e-10
dmaid_753                          -1.164e-10   7.72e-11     -1.508      0.132   -2.68e-10    3.49e-11
dmaid_757                          -5.166e-10   1.97e-10     -2.624      0.009   -9.03e-10   -1.31e-10
dmaid_770                          -1.637e-10   9.19e-11     -1.781      0.075   -3.44e-10    1.64e-11
dmaid_789                           6.185e-11   2.22e-10      0.279      0.780   -3.73e-10    4.96e-10
dmaid_803                          -1.819e-11   5.79e-11     -0.314      0.753   -1.32e-10    9.53e-11
dmaid_807                          -2.183e-11   4.88e-11     -0.447      0.655   -1.18e-10    7.39e-11
dmaid_819                           3.638e-12      5e-11      0.073      0.942   -9.44e-11    1.02e-10
dmaid_820                          -9.459e-11   6.97e-11     -1.357      0.175   -2.31e-10     4.2e-11
dmaid_825                           -1.71e-10   6.67e-11     -2.565      0.010   -3.02e-10   -4.03e-11
dmaid_855                          -2.547e-10   1.55e-10     -1.638      0.101   -5.59e-10    5.01e-11
dmaid_862                           -3.04e-10   1.18e-10     -2.582      0.010   -5.35e-10   -7.32e-11
==============================================================================
Omnibus:                     6655.488   Durbin-Watson:                   1.953
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           368037.835
Skew:                           1.702   Prob(JB):                         0.00
Kurtosis:                      28.890   Cond. No.                     2.45e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.21e-18. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [135]:
pred = (model.predict(test_df))
pred

20736     95000.0
15542    125000.0
6120     350000.0
12332    108000.0
1113     113000.0
           ...
12492    214000.0
9528     155000.0
649      160000.0
4604     200000.0
11932    161000.0
Length: 8637, dtype: float64

In [123]:
test_df['totalyearlycompensation']

20736     95000
15542    125000
6120     350000
12332    108000
1113     113000
          ...
12492    214000
9528     155000
649      160000
4604     200000
11932    161000
Name: totalyearlycompensation, Length: 8637, dtype: int64

In [130]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

LinearRegression()

In [136]:
y_test

20736     95000
15542    125000
6120     350000
12332    108000
1113     113000
          ...
12492    214000
9528     155000
649      160000
4604     200000
11932    161000
Name: totalyearlycompensation, Length: 8637, dtype: int64

In [140]:
lr_model_pred = lr_model.predict(X_test)
lr_model_pred

array([116636., 137344., 307905., ..., 187395., 182257., 100979.])

In [145]:
errors = abs(lr_model_pred - y_test)
errors.describe()

count    8.637000e+03
mean     3.415856e+11
std      3.174541e+13
min      7.000000e+00
25%      1.765400e+04
50%      3.813000e+04
75%      6.878300e+04
max      2.950275e+15
Name: totalyearlycompensation, dtype: float64

In [187]:
errors = errors.reset_index().drop(columns = "index")
errors.loc[errors.totalyearlycompensation > 3000000]

      totalyearlycompensation
3415             2.950275e+15
5676             4.096713e+06

In [197]:
lr_model_pred[3415]

2950274633809953.0

In [190]:
pred = pred.reset_index().drop(columns = "index")
pred.loc[3415]

0    159000.0
Name: 3415, dtype: float64

In [199]:
test_df = test_df.reset_index().drop(columns = "index")
pd.DataFrame(test_df.loc[3415])

,totalyearlycompensation,yearsofexperience,yearsatcompany,Masters_Degree,Bachelors_Degree,Doctorate_Degree,Highschool,Some_College,Race_Asian,Race_White,...,dmaid_770,dmaid_789,dmaid_803,dmaid_807,dmaid_819,dmaid_820,dmaid_825,dmaid_855,dmaid_862,dmaid_other
3415,159000.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [147]:
pd.DataFrame(lr_model_pred).describe()

                  0
count  8.637000e+03
mean   3.415858e+11
std    3.174541e+13
min   -4.507400e+04
25%    1.292460e+05
50%    1.910910e+05
75%    2.557520e+05
max    2.950275e+15

In [149]:
pd.DataFrame(y_test).describe()

       totalyearlycompensation
count             8.637000e+03
mean              1.987273e+05
std               1.356969e+05
min               1.000000e+04
25%               1.190000e+05
50%               1.750000e+05
75%               2.450000e+05
max               4.500000e+06

In [216]:
X_test = X_test.drop(labels = 9763)
y_test = y_test.drop(labels = 9763)

In [122]:
print("MAE on test data:",mean_absolute_error(pred,test_df['totalyearlycompensation']))

MAE on test data: 4.271200672293437e-10

In [141]:
print("MAE on test data:",mean_absolute_error(lr_model_pred,y_test))

MAE on test data: 341585633352.22046

In [129]:
print("MAE on test data:",np.sqrt(mean_squared_error(lr_model.predict(X_test),y_test)))

MAE on test data: 31745413287384.965

In [217]:
mod = LinearRegression()
mod.fit(X_train, y_train)

LinearRegression()

In [218]:
mod_pred = lr_model.predict(X_test)
print("MAE on test data:",mean_absolute_error(mod_pred,y_test))

MAE on test data: 55767.96838814266