In [87]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score,train_test_split, KFold, cross_val_predict
from sklearn.metrics import mean_squared_error,r2_score,roc_curve,auc,precision_recall_curve, accuracy_score, mean_absolute_error, \
recall_score, precision_score, confusion_matrix
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, ParameterGrid, StratifiedKFold, RandomizedSearchCV
from sklearn.ensemble import VotingRegressor, VotingClassifier, StackingRegressor, StackingClassifier, GradientBoostingRegressor,GradientBoostingClassifier, BaggingRegressor,BaggingClassifier,RandomForestRegressor,RandomForestClassifier,AdaBoostRegressor,AdaBoostClassifier
from sklearn.linear_model import LinearRegression,LogisticRegression, LassoCV, RidgeCV, ElasticNetCV
from sklearn.neighbors import KNeighborsRegressor
import itertools as it
import time as time
import xgboost as xgb
from pyearth import Earth
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
data = pd.read_csv('./Data/salary_data_cleaned.csv')
import warnings
warnings.filterwarnings(
    "ignore")

In [88]:
data = data.drop(columns='Unnamed: 0')
data

,totalyearlycompensation,yearsofexperience,yearsatcompany,Masters_Degree,Bachelors_Degree,Doctorate_Degree,Highschool,Some_College,Race_Asian,Race_White,...,dmaid_770,dmaid_789,dmaid_803,dmaid_807,dmaid_819,dmaid_820,dmaid_825,dmaid_855,dmaid_862,dmaid_other
0,400000,5.0,5.0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
1,136000,3.0,2.0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,337000,6.0,6.0,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
3,222000,4.0,4.0,1,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,187000,5.0,0.0,0,1,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21586,1470000,9.0,7.0,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
21587,4500000,20.0,14.0,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
21588,1605000,16.0,2.0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
21589,2372000,22.0,2.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
21590,4980000,17.0,0.0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1

In [3]:
data.totalyearlycompensation.describe()

count    2.159100e+04
mean     1.978458e+05
std      1.330927e+05
min      1.000000e+04
25%      1.190000e+05
50%      1.730000e+05
75%      2.450000e+05
max      4.980000e+06
Name: totalyearlycompensation, dtype: float64

In [64]:
X_train = pd.read_csv('./Data/X_train.csv').drop(columns='Unnamed: 0')
y_train = pd.read_csv('./Data/y_train.csv').drop(columns='Unnamed: 0')
X_test = pd.read_csv('./Data/X_test.csv').drop(columns='Unnamed: 0')
y_test = pd.read_csv('./Data/y_test.csv').drop(columns='Unnamed: 0')

In [65]:
col = X_train.columns
col = [str(x) for x in col]

In [66]:
alll = ""
for i in range(106):
    alll = alll + col[i] + "+"
alll = alll[:-1]
alll

'yearsofexperience+yearsatcompany+Masters_Degree+Bachelors_Degree+Doctorate_Degree+Highschool+Some_College+Race_Asian+Race_White+Race_Two_Or_More+Race_Black+Race_Hispanic+company_amazon+company_apple+company_cisco+company_facebook+company_google+company_ibm+company_intel+company_microsoft+company_oracle+company_other+company_salesforce+level_E5+level_IC4+level_L1+level_L2+level_L3+level_L4+level_L5+level_L6+level_L7+level_Senior Software Engineer+level_other+title_Business Analyst+title_Data Scientist+title_Hardware Engineer+title_Management Consultant+title_Product Designer+title_Product Manager+title_Software Engineer+title_Software Engineering Manager+title_Solution Architect+title_Technical Program Manager+title_other+tag_API Development (Back-End)+tag_Data+tag_DevOps+tag_Distributed Systems (Back-End)+tag_Full Stack+tag_ML / AI+tag_Product+tag_Technical+tag_User Experience (UX)+tag_Web Development (Front-End)+tag_other+gender_Female+gender_Male+gender_Other+dmaid_0+dmaid_501+dmaid_504+dmaid_505+dmaid_506+dmaid_508+dmaid_511+dmaid_512+dmaid_515+dmaid_517+dmaid_521+dmaid_524+dmaid_527+dmaid_528+dmaid_533+dmaid_534+dmaid_535+dmaid_539+dmaid_556+dmaid_560+dmaid_602+dmaid_609+dmaid_613+dmaid_616+dmaid_617+dmaid_618+dmaid_623+dmaid_635+dmaid_641+dmaid_652+dmaid_659+dmaid_669+dmaid_670+dmaid_675+dmaid_751+dmaid_753+dmaid_757+dmaid_770+dmaid_789+dmaid_803+dmaid_807+dmaid_819+dmaid_820+dmaid_825+dmaid_855+dmaid_862+dmaid_other'

In [89]:
model = sm.ols(formula = 'totalyearlycompensation~' + alll, data = data).fit()
model.summary()

SyntaxError: invalid syntax (<unknown>, line 1)

In [91]:
model = sm.ols(formula = 'totalyearlycompensation~' + '+'.join([x for x in col]), data = data).fit()
model.summary()

SyntaxError: invalid syntax (<unknown>, line 1)

In [82]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

LinearRegression()

In [83]:
pred = (lr_model.predict(X_test))
pred

array([[116636.],
       [137344.],
       [307905.],
       ...,
       [187395.],
       [182257.],
       [100979.]])

In [84]:
print("MAE on test data:",mean_absolute_error(pred,y_test))

MAE on test data: 341585633352.22046